---
name: F1 database updater

on: workflow_dispatch

jobs:
  main:
    name: Update F1 database
    runs-on: ubuntu-latest

    services:
      database:
        image: thibaultcne/race-tech:db
        env:
          MYSQL_DATABASE: f1db
          MYSQL_USER: user
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 13306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Verify f1db DB exists
        run: |
          export MYSQL_PWD=password
          mysql --host 127.0.0.1 --port 13306 -uroot -e "SHOW DATABASES LIKE 'f1db'"

      - name: Setup env variables
        shell: bash
        run: |
          # Query the database for the latest F1 data
          export MYSQL_PWD=password
          params=$(echo "SELECT r.round, c.country FROM circuits AS c JOIN races AS r ON c.circuitId = r.circuitId WHERE r.date <= '$(date +'%Y-%m-%d')' ORDER BY r.date DESC LIMIT 1" | mysql -h 127.0.0.1 -P 13306 --protocol=tcp -u root -D f1db | tail -1 | xargs)
          echo "Params=$params" >> $GITHUB_ENV

      - name: Check params value
        run: echo ${{ env.Params }}

      - name: Create sql dump
        run: |
          export MYSQL_PWD=password
          mysqldump --host 127.0.0.1 --port 13306 -uroot f1db > f1db.sql
          tar -czvf f1db.sql.gz f1db.sql

      - name: Upload sql dump
        uses: actions/upload-artifact@v2
        with:
          name: f1db.sql.gz
          path: f1db.sql.gz
